// Code generated by github.com/gobuffalo/packr. DO NOT EDIT

package example

import "github.com/gobuffalo/packr"

// You can use the "packr clean" command to clean up this,
// and any other packr generated files.
func init() {
		packr.PackJSONBytes("./assets", "app.css", "\"Ym9keSB7CiAgYmFja2dyb3VuZDogcmVkOwp9Cg==\"")
		packr.PackJSONBytes("./assets", "app.js", "\"YWxlcnQoImhlbGxvISIpOwo=\"")
		packr.PackJSONBytes("./bar", "bar.html", "\"\"")
		packr.PackJSONBytes("./constant", "constant.html", "\"\"")
		packr.PackJSONBytes("./foo", "bar.go", "\"cGFja2FnZSBmb28KCmltcG9ydCAiZ2l0aHViLmNvbS9nb2J1ZmZhbG8vcGFja3IiCgpmdW5jIGluaXQoKSB7CglwYWNrci5OZXdCb3goIi4uL2Fzc2V0cyIpCn0K\"")
		packr.PackJSONBytes("./foo", "foo.go", "\"cGFja2FnZSBmb28KCmltcG9ydCAiZ2l0aHViLmNvbS9nb2J1ZmZhbG8vcGFja3IiCgpmdW5jIGluaXQoKSB7CglwYWNrci5OZXdCb3goIi4uL3RlbXBsYXRlcyIpCn0K\"")
		packr.PackJSONBytes("./sf", "foo.html", "\"ICA8IURPQ1RZUEUgaHRtbD4KICA8aHRtbD4KICAgIDxoZWFkPgogICAgICA8bWV0YSBjaGFyc2V0PSJVVEYtOCIgLz4KICAgICAgPG1ldGEgbmFtZT0idmlld3BvcnQiIGNvbnRlbnQ9IndpZHRoPWRldmljZS13aWR0aCIgLz4KICAgICAgPHRpdGxlPkZvbzwvdGl0bGU+CiAgICA8L2hlYWQ+CiAgICA8Ym9keT4KICAgICAgYm9keQogICAgPC9ib2R5PgogIDwvaHRtbD4K\"")
		packr.PackJSONBytes("./templates", "index.html", "\"PCFET0NUWVBFIGh0bWw+CjxodG1sPgogIDxoZWFkPgogICAgPG1ldGEgY2hhcnNldD0idXRmLTgiIC8+CiAgICA8bWV0YSBuYW1lPSJ2aWV3cG9ydCIgY29udGVudD0id2lkdGg9ZGV2aWNlLXdpZHRoIiAvPgogICAgPHRpdGxlPklOREVYPC90aXRsZT4KICAgIGxpbmsKICA8L2hlYWQ+CiAgPGJvZHk+CiAgICBib2R5CiAgPC9ib2R5Pgo8L2h0bWw+Cg==\"")
		packr.PackJSONBytes("./variable", "variable.html", "\"\"")
}
