builds:
-
  goos:
    - darwin
    - linux
    - windows
  env:
    - CGO_ENABLED=0
  main: ./packr/main.go
  binary: packr

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brew:
  github:
    owner: gobuffalo
    name: homebrew-tap
  homepage: https://github.com/gobuffalo/packr
  description: The simple and easy way to embed static files into Go binaries.
  test: |
    system "#{bin}/packr", "-h"
