// Code generated by github.com/gobuffalo/packr. DO NOT EDIT.

package main

import "github.com/gobuffalo/packr"

// You can use the "packr clean" command to clean up this,
// and any other packr generated files.
func init() {
	packr.PackJSONBytes("../good/templates", "woot.txt", "\"d29vdCEhIQo=\"")
	packr.PackJSONBytes("../good/templates", "yay.txt", "\"eWF5ISEhCg==\"")
	packr.PackJSONBytes("../skipme/templates", "skippy.gif", "\"\"")
}
