// Code generated by github.com/gobuffalo/packr. DO NOT EDIT.

package box

import "github.com/gobuffalo/packr"

// You can use the "packr clean" command to clean up this,
// and any other packr generated files.
func init() {
	packr.PackJSONBytes("../box/templates", "generated.go.plush", "\"Ly8gQ29kZSBnZW5lcmF0ZWQgYnkgZ2l0aHViLmNvbS9nb2J1ZmZhbG8vcGFja3IuIERPIE5PVCBFRElULgoKcGFja2FnZSA8JT0gb3B0cy5QYWNrYWdlICU+CgppbXBvcnQgImdpdGh1Yi5jb20vZ29idWZmYWxvL3BhY2tyIgoKLy8gWW91IGNhbiB1c2UgdGhlICJwYWNrciBjbGVhbiIgY29tbWFuZCB0byBjbGVhbiB1cCB0aGlzLAovLyBhbmQgYW55IG90aGVyIHBhY2tyIGdlbmVyYXRlZCBmaWxlcy4KZnVuYyBpbml0KCkgewoJPCU9IGZvciAoZikgaW4gZmlsZXMgeyAlPgoJcGFja3IuUGFja0hleEd6aXAoIjwlPSBmLkJveCAlPiIsICI8JT0gZi5OYW1lICU+IiwgIjwlPSBmLlBhY2tlZCAlPiIpCgk8JSB9ICU+Cn0K\"")
}
