// Code generated by github.com/gobuffalo/packr. DO NOT EDIT.

package fixtures

import "github.com/gobuffalo/packr"

// You can use the "packr clean" command to clean up this,
// and any other packr generated files.
func init() {
	packr.PackJSONBytes("../fixtures", "fixtures.go", "\"cGFja2FnZSBmaXh0dXJlcwoKaW1wb3J0ICJnaXRodWIuY29tL2dvYnVmZmFsby9wYWNrciIKCnZhciBCb3ggPSBwYWNrci5OZXdCb3goIi4uL2ZpeHR1cmVzIikK\"")
	packr.PackJSONBytes("../fixtures", "foo/a.txt", "\"\"")
	packr.PackJSONBytes("../fixtures", "foo/bar/b.txt", "\"\"")
	packr.PackJSONBytes("../fixtures", "goodbye.txt", "\"Z29vZGJ5ZSBjcnVlbCB3b3JsZCEK\"")
	packr.PackJSONBytes("../fixtures", "hello.txt", "\"aGVsbG8gd29ybGQhCg==\"")
	packr.PackJSONBytes("../fixtures", "index.html", "\"PGgxPkluZGV4ITwvaDE+Cg==\"")
}
